---
driver:
  name: vagrant
driver_config:
  forward_agent: true
  customize:
    memory: 2048
    cpus: 4
    cpuexecutioncap: 50
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
  network:
    - ["forwarded_port", {guest: 8080, host: 8080}] # forward Jenkins
    - ["forwarded_port", {guest: 8889, host: 8889}] # forward Chef-Zero

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.4
  data_bags_path: ./test/integration/data_bags
  encrypted_data_bag_secret_key_path: ./.chef/encrypted_data_bag_secret

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[u2i-jenkins]
    attributes:
      jenkins:
        executor:
          timeout: 360
        master:
          port: 8080
      u2i-jenkins:
        config:
          gitconfig:
            name: Jenkins
            email: jenkins@u2i.com
          numExecutors: 4
          admins:
            - michal.knapik@u2i.com
          domain: localhost
          address: localhost
          plugins:
