---
driver:
  name: vagrant
driver_config:
  forward_agent: true
  customize:
    memory: 2048
    cpus: 4
    cpuexecutioncap: 50
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
  use_cachier_plugin: true
  network:
    - ["forwarded_port", {guest: 8080, host: 8080}] # forward Jenkins
    - ["forwarded_port", {guest: 8889, host: 8889}] # forward Chef-Zero

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.4
  data_bags_path: ./test/integration/data_bags
  encrypted_data_bag_secret_key_path: ./.chef/encrypted_data_bag_secret

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[u2i-jenkins]
      - recipe[u2i-jenkins::jobs]
      - recipe[u2i-jenkins::auth]
    attributes:
      jenkins:
        executor:
          timeout: 360
        master:
          port: 8080
      rvm:
        rvmrc:
          rvm_autolibs_flag: disabled
      u2i-jenkins:
        user: vagrant
        config:
          gitconfig:
            name: Jenkins
            email: jenkins@u2i.com
          numExecutors: 4
          admins:
            - michal.knapik@u2i.com
          domain: localhost
          plugins:

        jobs:
          u2i-jenkins-matrix_project:
            repository: mknapik/u2i-jenkins-matrix_project
            type: matrix
            lang: ruby
            ruby_version: 2.1.5
            branches:
            - master
            - pr
            matrix:
              sequentially: true
              combination_filter: "!(RUBY_VERSION==&quot;1.8.7&quot; &amp;&amp; RAILS_VERSION==&quot;4&quot;)"
              axes:
                RUBY_VERSION:
                - 1.9.3-p547
                - 2.1.5
                RAILS_VERSION:
                - 2
                - 3
                - 4
            credential_name: u2i-jenkins-matrix_project
            builders:
              - hudson.tasks.Shell:
                  command: |
                    rm -f Gemfile.lock
                    bundle &gt; .bundle.install

                    bundle exec rake ci:setup:rspec spec

          u2i-jenkins-rails_project:
            repository: mknapik/u2i-jenkins-rails_project
            type: freestyle
            lang: ruby
            ruby_version: 2.1.5
            branches:
            - master
            - development
            - pr
            ws_cleanup: true
            rubocop:
              min: 7
              max: 8
              unstable: 9
            coverage:
              code:
                unstable: 1
                unhealthy: 2
                healthy: 3
              total:
                unstable: 4
                unhealthy: 5
                healthy: 6
            rails: true
            brakeman: true
            credential_name: u2i-jenkins-rails_project
            builders:
              - hudson.tasks.Shell:
                  command: |
                    set +e
                    cp /var/proj/${PROJECT_NAME}/config/*.yml config/
                    cp /var/proj/${PROJECT_NAME}/config/${BRANCH}/*.yml config/
              - hudson.tasks.Shell:
                  command: |
                    bundle > .bundle.install

                    bundle exec rake db:create:all
                    bundle exec rake db:migrate

                    bundle exec rake ci:setup:minitest test

                    bundle exec rake db:drop:all
