name             'u2i-jenkins'
maintainer       'Michał Knapik'
maintainer_email 'michal.knapik@u2i.com'
license          'All rights reserved'
description      'Installs/Configures u2i-jenkins'
long_description 'Installs/Configures u2i-jenkins'
version          '0.1.0'

depends 'java'
depends 'jenkins'
depends 'rvm'
depends 'ssh_known_hosts'
depends 'apt'

supports 'ubuntu'
